
# Site settings
title: Humanidades_ Filos digítal 
author: 
name: Santiago Aguilar Luna
email: sanUNAM20@gmail.com
description: Investigaciones sobre las humanidades digítales

# Build settings
remote_theme: jeky11/minima



