
# Site settings
title: Humanidades_ Filos digítal 
author: Santiago Aguilar Luna 
name: Santiago 
email: sanUNAM20@gmail.com
description: "Investigaciones sobre las humanidades digítales"

# Build settings
remote_theme: jeky11/minima



